// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-recent-sales.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_sales_default = defineTool({
  name: "list_recent_sales",
  title: "List recent sales",
  description: "List the signed-in merchant's most recent POS sales (invoice number, total, payment method, date).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many sales to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("sales").select("invoice_number,total_amount,payment_method,payment_status,customer_name,sale_date").order("sale_date", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sales: data }
    };
  }
});

// src/lib/mcp/tools/inventory-summary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var inventory_summary_default = defineTool2({
  name: "inventory_summary",
  title: "Inventory summary",
  description: "Summarize the merchant's inventory: total devices, available devices, accessory SKUs, and low-stock accessories.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const [{ data: devices, error: dErr }, { data: accessories, error: aErr }] = await Promise.all([
      sb.from("devices").select("status,cost"),
      sb.from("accessories").select("quantity,min_quantity,cost")
    ]);
    if (dErr || aErr) {
      return {
        content: [{ type: "text", text: (dErr || aErr).message }],
        isError: true
      };
    }
    const totalDevices = devices?.length ?? 0;
    const availableDevices = (devices ?? []).filter((d) => d.status === "available").length;
    const accessorySkus = accessories?.length ?? 0;
    const lowStock = (accessories ?? []).filter(
      (a) => Number(a.quantity) <= Number(a.min_quantity ?? 5)
    ).length;
    const inventoryValue = (devices ?? []).filter((d) => d.status === "available").reduce((s, d) => s + Number(d.cost || 0), 0) + (accessories ?? []).reduce(
      (s, a) => s + Number(a.cost || 0) * Number(a.quantity || 0),
      0
    );
    const summary = { totalDevices, availableDevices, accessorySkus, lowStock, inventoryValue };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-active-repairs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_active_repairs_default = defineTool3({
  name: "list_active_repairs",
  title: "List active repair orders",
  description: "List active (non-delivered, non-cancelled) repair orders for the signed-in merchant.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("repair_orders").select("repair_number,customer_name,customer_phone,device_type,device_brand,device_model,status,estimated_cost,received_at").not("status", "in", "(delivered,cancelled)").order("received_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { repairs: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ynwddyxzypbcftlevuam";
var mcp_default = defineMcp({
  name: "wasil-os-mcp",
  title: "Wasil OS",
  version: "0.1.0",
  instructions: "Tools for the signed-in Wasil OS merchant: read recent POS sales, inventory summary, and active repair orders. All data is scoped to the merchant via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_sales_default, inventory_summary_default, list_active_repairs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
